# Uncomment this line to define a global platform for your project
# platform :ios, '8.0'
# Uncomment this line if you're using Swift
use_frameworks!

target 'Likes' do

pod 'RESideMenu', '~> 4.0.7'

pod 'UIColor_Hex_Swift', '~> 2.1'

pod 'Alamofire', '~> 3.1.2'

pod 'Ono'

end

